# Generated by Django 4.0.6 on 2022-07-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('creditos', models.PositiveSmallIntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
